### PR TITLE
feat: node 20 version support

### LINKED ISSUE #345: Node.js 16 actions are deprecated
Basically a warning given by GitHub action execution.

> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: thollander/actions-comment-pull-request@v2. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

### PR DESCRIPTION
**Pull request by thollander**
- Adapt node runtime version to LTS
- No major bump as there is no change on the output 

Closes #345

### CODE REVIEW

**Comment by Disservin** [comment]
@thollander this would fix #345 any updates?

**Comment by ViacheslavKudinov** [comment]
Hi @thollander 
any progress with moving to Node20 ?
Thank you in advance.

**Review by mgrybyk — APPROVED** [review]

**Review by kdawgwilk — APPROVED** [review]

**Comment by mgrybyk** [comment]
@thollander hello, will you be able to release the node20 PR?

**Review by KylePeterDavies — APPROVED** [review]

**Comment by thollander** [comment]
Sorry for the delay guys, pushing it to `2.5.0`

**Pull request merged**
