### PR TITLE
docs: fix inputs in README.md

### PR DESCRIPTION
**Pull request by kkebo**
This is similar to #395.

### CODE REVIEW

**Comment by koppor** [comment]
Please include 

```markdown
## Update notice 
  
 If you update from `v2` to `v3`, you need to replace `comment_tag` by `comment-tag`.
```

**Comment by kkebo** [comment]
@koppor Thanks. I cherry-picked your commit.

**Comment by ViacheslavKudinov** [comment]
To address https://github.com/thollander/actions-comment-pull-request/issues/397

**Comment by thollander** [comment]
Thanks for your contribution, was done in https://github.com/thollander/actions-comment-pull-request/pull/409

**Pull request closed without merging**
